name: rcet_shuttle_bus
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  permission_handler: ^11.3.1
  location: ^7.0.1
  http: ^1.2.2
  google_fonts: ^6.2.1
  geolocator: ^13.0.2
  device_info_plus: ^11.2.0
  shared_preferences: ^2.3.5
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2  # Add flutter_launcher_icons to generate app icon

flutter_icons:
  android: true   # Generate Android icons
  ios: true       # Generate iOS icons
  image_path: "assets/iiccoonn.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/iiccoonn.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/
