// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPWqZkaQGvsjYFsmJ9_fXNF-v3X3n9Xo4',
    appId: '1:136875193131:android:014b0f901a0f02ceb24b6e',
    messagingSenderId: '136875193131',
    projectId: 'rcetshuttleservice',
    storageBucket: 'rcetshuttleservice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIzz7-Xdu0x2bNzY-3I5QTvGVnjjX421c',
    appId: '1:136875193131:ios:39b0d8fab86350c4b24b6e',
    messagingSenderId: '136875193131',
    projectId: 'rcetshuttleservice',
    storageBucket: 'rcetshuttleservice.firebasestorage.app',
    iosBundleId: 'com.example.gef',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaCHahHHVI58Q2_BfWD5MFGc6fes3gsMs',
    appId: '1:136875193131:web:c6aac09c0c9448ceb24b6e',
    messagingSenderId: '136875193131',
    projectId: 'rcetshuttleservice',
    authDomain: 'rcetshuttleservice.firebaseapp.com',
    storageBucket: 'rcetshuttleservice.firebasestorage.app',
    measurementId: 'G-V3P6GZ8KKT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIzz7-Xdu0x2bNzY-3I5QTvGVnjjX421c',
    appId: '1:136875193131:ios:39b0d8fab86350c4b24b6e',
    messagingSenderId: '136875193131',
    projectId: 'rcetshuttleservice',
    storageBucket: 'rcetshuttleservice.firebasestorage.app',
    iosBundleId: 'com.example.gef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaCHahHHVI58Q2_BfWD5MFGc6fes3gsMs',
    appId: '1:136875193131:web:a774419a9cd4ebe2b24b6e',
    messagingSenderId: '136875193131',
    projectId: 'rcetshuttleservice',
    authDomain: 'rcetshuttleservice.firebaseapp.com',
    storageBucket: 'rcetshuttleservice.firebasestorage.app',
    measurementId: 'G-7W5P3BFK3G',
  );

}